---

- include_vars: env_variables

- name: Creating a repository file for Kubernetes
  file:
    path: /etc/yum.repos.d/kubernetes.repo
    state: touch
  become: yes    

- name: Adding repository details in Kubernetes repo file.
  blockinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    block: |
     [kubernetes]
     name=Kubernetes
     baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
     enabled=1
     gpgcheck=1
     repo_gpgcheck=1
     gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
     exclude=kube*  
  become: yes

- name: Installing Docker and kubectl, kubeadm
  shell: |
    yum -y install docker
    setenforce 0
    sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
    yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
  become: yes  
  args:
    warn: false

- name: Starting and Enabling the required services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ services }}"
  become: yes

- name: Enabling Bridge Firewall Rule
  shell: |
    cat <<EOF >  /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    EOF
    sysctl --system
    modprobe br_netfilter
  become: yes