apiVersion: v1
kind: Service
metadata:
  name: cs-port
  labels:
    name: cs-port
  namespace: linuxjobber  
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30700
    name: cs-api
    targetPort: 5000
  - port: 5100
    nodePort: 30800
    targetPort: 5100
    name: cs-home
  selector:
    app: chatscrum      
