apiVersion: v1
kind: Service
metadata:
  name: csdb
  namespace: linuxjobber
spec:
  type: ClusterIP
  ports:
  - name: csdb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: chatscrum
