apiVersion: v1
kind: Service
metadata:
  name: grader
  namespace: linuxjobber
spec:
  type: ClusterIP
  ports:
  - name: grader
    port: 58500
    protocol: TCP
    targetPort: 58500
  selector:
    app: linuxjobber 