apiVersion: v1
kind: Service
metadata:
  name: ljdb
  namespace: linuxjobber
spec:
  type: ClusterIP
  ports:
  - name: ljdb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: linuxjobber 