apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: linuxjobber
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: linuxjobber 